export const FETCH_USER_INFO = 'FETCH_USER_INFO';       //拉取学生信息 -> ClassInfo
export const FETCH_LESSON_INFO = 'FETCH_LESSON_INFO';   //拉取课程信息 -> ClassInfo
export const FETCH_CLASS_INFO = 'FETCH_CLASS_INFO';     //拉取学生上课详情 -> StudyInfo
export const FETCH_STUDENT_LIST = 'FETCH_STUDENT_LIST'; //拉取学生列表 -> StudentList
export const FETCH_SATISFIED_LIST = 'FETCH_SATISFIED_LIST';//拉取满意度反馈 -> ClassInfo
export const FETCH_HOMEWORK_LIST_USER_UNREVIEW = 'FETCH_HOMEWORK_LIST_USER_UNREVIEW';// 
export const FETCH_HOMEWORK_LIST_USER_REVIEWED = 'FETCH_HOMEWORK_LIST_USER_REVIEWED';
export const FETCH_HOMEWORK_LIST_ALL_UNREVIEW = 'FETCH_HOMEWORK_LIST_ALL_UNREVIEW';
export const FETCH_HOMEWORK_LIST_ALL_REVIEWED = 'FETCH_HOMEWORK_LIST_ALL_REVIEWED';

export const FETCH_AUTHORITIES = 'FETCH_AUTHORITIES';